<?php

namespace ContainerFJy52T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9u06H1eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9u06H1e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\HelloWorldController::sendMail' => ['privates', '.service_locator.heJ666n.App\\Controller\\HelloWorldController::sendMail()', 'getHelloWorldControllersendMailService', true],
            'App\\Controller\\PokemonController::index' => ['privates', '.service_locator.LFsKSqA.App\\Controller\\PokemonController::index()', 'getPokemonControllerindexService', true],
            'App\\Controller\\PokemonController::create' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\PokemonController::create()', 'getPokemonControllercreateService', true],
            'App\\Controller\\PokemonController::show' => ['privates', '.service_locator.6u3CLkp.App\\Controller\\PokemonController::show()', 'getPokemonControllershowService', true],
            'App\\Controller\\PokemonController::update' => ['privates', '.service_locator.1rKo8fK.App\\Controller\\PokemonController::update()', 'getPokemonControllerupdateService', true],
            'App\\Controller\\PokemonTypeController::index' => ['privates', '.service_locator.08FVjDw.App\\Controller\\PokemonTypeController::index()', 'getPokemonTypeControllerindexService', true],
            'App\\Controller\\PokemonTypeController::handleCreate' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\PokemonTypeController::handleCreate()', 'getPokemonTypeControllerhandleCreateService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.UDxVJk_.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.db.LmRj.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.f8pLBFr.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\HelloWorldController:sendMail' => ['privates', '.service_locator.heJ666n.App\\Controller\\HelloWorldController::sendMail()', 'getHelloWorldControllersendMailService', true],
            'App\\Controller\\PokemonController:index' => ['privates', '.service_locator.LFsKSqA.App\\Controller\\PokemonController::index()', 'getPokemonControllerindexService', true],
            'App\\Controller\\PokemonController:create' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\PokemonController::create()', 'getPokemonControllercreateService', true],
            'App\\Controller\\PokemonController:show' => ['privates', '.service_locator.6u3CLkp.App\\Controller\\PokemonController::show()', 'getPokemonControllershowService', true],
            'App\\Controller\\PokemonController:update' => ['privates', '.service_locator.1rKo8fK.App\\Controller\\PokemonController::update()', 'getPokemonControllerupdateService', true],
            'App\\Controller\\PokemonTypeController:index' => ['privates', '.service_locator.08FVjDw.App\\Controller\\PokemonTypeController::index()', 'getPokemonTypeControllerindexService', true],
            'App\\Controller\\PokemonTypeController:handleCreate' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\PokemonTypeController::handleCreate()', 'getPokemonTypeControllerhandleCreateService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.UDxVJk_.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.db.LmRj.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.f8pLBFr.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AuthController::login' => '?',
            'App\\Controller\\HelloWorldController::sendMail' => '?',
            'App\\Controller\\PokemonController::index' => '?',
            'App\\Controller\\PokemonController::create' => '?',
            'App\\Controller\\PokemonController::show' => '?',
            'App\\Controller\\PokemonController::update' => '?',
            'App\\Controller\\PokemonTypeController::index' => '?',
            'App\\Controller\\PokemonTypeController::handleCreate' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AuthController:login' => '?',
            'App\\Controller\\HelloWorldController:sendMail' => '?',
            'App\\Controller\\PokemonController:index' => '?',
            'App\\Controller\\PokemonController:create' => '?',
            'App\\Controller\\PokemonController:show' => '?',
            'App\\Controller\\PokemonController:update' => '?',
            'App\\Controller\\PokemonTypeController:index' => '?',
            'App\\Controller\\PokemonTypeController:handleCreate' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
        ]);

        if (isset($container->privates['.service_locator.9u06H1e'])) {
            return $container->privates['.service_locator.9u06H1e'];
        }

        return $container->privates['.service_locator.9u06H1e'] = $instance;
    }
}
