<?php

namespace ContainerFJy52T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBootstrapButtonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\BootstrapButton' autowired service.
     *
     * @return \App\Twig\Components\BootstrapButton
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Components'.\DIRECTORY_SEPARATOR.'BootstrapButton.php';

        $container->factories['service_container']['App\\Twig\\Components\\BootstrapButton'] = function ($container) {
            return new \App\Twig\Components\BootstrapButton();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\BootstrapButton']($container);
    }
}
