<?php

namespace ContainerFJy52T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPokemonControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1rKo8fK.App\Controller\PokemonController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pokemon' => ['privates', '.errored..service_locator.1rKo8fK.App\\Entity\\Pokemon', NULL, 'Cannot autowire service ".service_locator.1rKo8fK": it needs an instance of "App\\Entity\\Pokemon" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'pokemon' => 'App\\Entity\\Pokemon',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\PokemonController::update()', $container);

        if (isset($container->privates['.service_locator.1rKo8fK.App\\Controller\\PokemonController::update()'])) {
            return $container->privates['.service_locator.1rKo8fK.App\\Controller\\PokemonController::update()'];
        }

        return $container->privates['.service_locator.1rKo8fK.App\\Controller\\PokemonController::update()'] = $instance;
    }
}
