<?php

namespace ContainerFJy52T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPokemonControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6u3CLkp.App\Controller\PokemonController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6u3CLkp.App\\Controller\\PokemonController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pokemon' => ['privates', '.errored..service_locator.6u3CLkp.App\\Entity\\Pokemon', NULL, 'Cannot autowire service ".service_locator.6u3CLkp": it needs an instance of "App\\Entity\\Pokemon" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'pokemon' => 'App\\Entity\\Pokemon',
        ]))->withContext('App\\Controller\\PokemonController::show()', $container);
    }
}
