<?php

namespace ContainerFJy52T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPokemonTypeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.08FVjDw.App\Controller\PokemonTypeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.08FVjDw.App\\Controller\\PokemonTypeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pokemonTypeRepository' => ['privates', 'App\\Repository\\PokemonTypeRepository', 'getPokemonTypeRepositoryService', true],
        ], [
            'pokemonTypeRepository' => 'App\\Repository\\PokemonTypeRepository',
        ]))->withContext('App\\Controller\\PokemonTypeController::index()', $container);
    }
}
