<?php

namespace ContainerFJy52T1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPokemonControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LFsKSqA.App\Controller\PokemonController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LFsKSqA.App\\Controller\\PokemonController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pokemonRepository' => ['privates', 'App\\Repository\\PokemonRepository', 'getPokemonRepositoryService', true],
        ], [
            'pokemonRepository' => 'App\\Repository\\PokemonRepository',
        ]))->withContext('App\\Controller\\PokemonController::index()', $container);
    }
}
