<?php

namespace ContainerT67WSxd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBootstrapCardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\BootstrapCard' autowired service.
     *
     * @return \App\Twig\Components\BootstrapCard
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Components'.\DIRECTORY_SEPARATOR.'BootstrapCard.php';

        $container->factories['service_container']['App\\Twig\\Components\\BootstrapCard'] = function ($container) {
            return new \App\Twig\Components\BootstrapCard();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\BootstrapCard']($container);
    }
}
