<?php

namespace ContainerT67WSxd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.twig_component.component_factory' shared service.
     *
     * @return \Symfony\UX\TwigComponent\ComponentFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-twig-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ComponentFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-twig-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ComponentTemplateFinderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-twig-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ComponentTemplateFinder.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['ux.twig_component.component_factory'])) {
            return $container->privates['ux.twig_component.component_factory'];
        }
        $b = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['ux.twig_component.component_factory'])) {
            return $container->privates['ux.twig_component.component_factory'];
        }

        $instance = new \Symfony\UX\TwigComponent\ComponentFactory(new \Symfony\UX\TwigComponent\ComponentTemplateFinder(($container->privates['twig.loader.native_filesystem'] ?? self::getTwig_Loader_NativeFilesystemService($container)), 'components/'), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'BootstrapButton' => [false, 'App\\Twig\\Components\\BootstrapButton', 'getBootstrapButtonService', true],
            'BootstrapCard' => [false, 'App\\Twig\\Components\\BootstrapCard', 'getBootstrapCardService', true],
        ], [
            'BootstrapButton' => '?',
            'BootstrapCard' => '?',
        ]), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)), $a, ['BootstrapButton' => ['expose_public_props' => true, 'attributes_var' => 'attributes', 'key' => 'BootstrapButton', 'service_id' => 'App\\Twig\\Components\\BootstrapButton', 'class' => 'App\\Twig\\Components\\BootstrapButton', 'template' => 'components/BootstrapButton.html.twig', 'pre_mount' => [], 'mount' => ['mount'], 'post_mount' => []], 'BootstrapCard' => ['expose_public_props' => true, 'attributes_var' => 'attributes', 'key' => 'BootstrapCard', 'service_id' => 'App\\Twig\\Components\\BootstrapCard', 'class' => 'App\\Twig\\Components\\BootstrapCard', 'template' => 'components/BootstrapCard.html.twig', 'pre_mount' => [], 'mount' => ['mount'], 'post_mount' => []]], ['App\\Twig\\Components\\BootstrapButton' => 'BootstrapButton', 'App\\Twig\\Components\\BootstrapCard' => 'BootstrapCard'], $b);

        if (isset($container->privates['ux.twig_component.component_factory'])) {
            return $container->privates['ux.twig_component.component_factory'];
        }

        return $container->privates['ux.twig_component.component_factory'] = $instance;
    }
}
