<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5r6WUbV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5r6WUbV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5r6WUbV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5r6WUbV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5r6WUbV\App_KernelDevDebugContainer([
    'container.build_hash' => '5r6WUbV',
    'container.build_id' => 'f84f7f00',
    'container.build_time' => 1775648077,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5r6WUbV');
