<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJOkNSxl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJOkNSxl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJOkNSxl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJOkNSxl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJOkNSxl\App_KernelDevDebugContainer([
    'container.build_hash' => 'JOkNSxl',
    'container.build_id' => '6b61f70b',
    'container.build_time' => 1776158549,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJOkNSxl');
