<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZtUuHjR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZtUuHjR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZtUuHjR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZtUuHjR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZtUuHjR\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZtUuHjR',
    'container.build_id' => 'e4bec4fc',
    'container.build_time' => 1776084287,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZtUuHjR');
